from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/report',views.report),
    path('admin/report/ad',views.reporta),
    path('admin/report/report_detail',views.report),
    path('admin/report/report_detail/get',views.get),
    path('',views.home),
    path('a/userlogin',views.home1),
    path('a/chori',views.chori),
    path('customer_info/chori/',views.chori),
    path('customer_info/chori',views.chori),
    path('a/gate', views.gate),
    path('customer_info/gate/', views.gate),
    path('customer_info/gate', views.gate),
    path('a/tablechair', views.tablechair),
    path('customer_info/tablechair/', views.tablechair),
    path('customer_info/tablechair', views.tablechair),
    path('a/paat', views.paat),
    path('customer_info/paat', views.paat),
    path('a/others', views.others),
    path('customer_info/others', views.others),
    path('customer_info/userregister',views.userregister),
    path('customer_info/userregister/createaccount',views.CreateAccount),
    path('customer_info/userlogin',views.userlogin),
    path('customer_info',views.userlogin),
    path('delete/product/<str:pcode>',views.deleteproduct),
    path('delete/product/<str:pcode>',views.deleteproduct),
    path('customer_info/logout/<int:ul>',views.logout),
    path('customer_info/profile',views.profile),
    path('customer_info/inqueryorder', views.inquery_order),
    path('customer_info/profile/ChangeName',views.changesName),
    path('customer_info/profile/ChangeMobileNumber',views.ChangeMobileNumber),
    path('customer_info/profile/ChangeEmail',views.ChangeEmail),
    path('customer_info/profile/ChangeEmail/changed',views.ChangedEmail),
    path('customer_info/profile/ChangePassword',views.changesPassword),
    path('customer_info/profile/ChangeAddress',views.changesAddress),
    path('customer_info/profile/ChangeImage',views.changesImage),
    path('customer_info/profile/DeleteAccount',views.DeleteAccount),
    path('customer_info/<str:uname>/usercart/<str:p_id>',views.usercart),
    path('customer_info/<str:uname>/usercart/<str:p_id>/<str:p_color>',views.usercart),
    path('customer_info/myorder',views.Myoreder),
    path('customer_info/myorder/<int:o_id1>',views.Myorederdetail),
    path('<str:product_type>/<str:p_code>',views.disp_chori),
    path('customer_info/myorder/<str:product_type>/<str:p_code>',views.disp_chori),
    path('<str:product_type>/<str:p_code>/CP',views.disp_choriI),
    path('customer_info/inqueryorder/newinquery',views.new_inquery_order),
    path('customer_info/inqueryorder/inqueryhistory',views.inqueryhistory),
    path('customer_info/inqueryorder/newinquery/newinqsub',views.new_inquery_order),
    path('customer_info/inqueryorder/inquerydata',views.inqdata),
    path('customer_info/inqueryorder/inquerydata/placeorder',views.inqdata),
    path('<str:product_type>/<str:p_code>', views.disp_chori),
    path('<str:product_type>/<str:p_code>/order', views.finalorder),
    path('customer_info/<str:product_type>/<str:p_code>', views.disp_chori),
    path('customer_info/myorder',views.Myoreder),
    path('<str:product_type>/<str:p_code>/<str:p_color>/<str:p_price>/<str:no>/addcart',views.tempcart),
    path('<str:product_type>/<str:p_code>/<str:p_color>/<str:p_price>/<str:no>/<str:iqu_id>/addcart',views.tempcartI),
    path('deliyes/deliaddchno/addressno/conform/<str:sub_totel>',views.filedorderwithdeli),
    path('delino/deliaddchno/addressno/conform/<str:sub_totel>',views.filedorder),
    path('customer_info/myorder/<str:o_id>/Bill/Download',views.GenBill),


]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)