# Generated by Django 2.2.5 on 2020-03-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_info', '0027_auto_20200303_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(blank=True, max_length=64, null=True)),
                ('c_amt', models.CharField(blank=True, help_text='totle amount of money', max_length=10, null=True)),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_detail')),
                ('d_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.delivery')),
                ('o_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_order')),
            ],
        ),
    ]
