# Generated by Django 2.2.5 on 2020-03-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_receipt',
            name='c_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.customer_detail'),
        ),
        migrations.AlterField(
            model_name='customer_receipt',
            name='o_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.customer_order'),
        ),
    ]
