# Generated by Django 2.2.5 on 2020-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_receipt', '0002_auto_20200304_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_receipt',
            name='c_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer_receipt',
            name='c_mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
