# Generated by Django 2.2.5 on 2020-01-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0005_delete_gadge'),
        ('employee_master', '0002_auto_20191213_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_detail',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('e_mail', models.EmailField(max_length=254)),
                ('c_add', models.TextField(max_length=100)),
                ('com_per_name', models.CharField(default=None, max_length=20, null=True, verbose_name='comapany person name')),
                ('com_per_no', models.CharField(help_text='mobile_no if customer is not company', max_length=10, null=True, verbose_name='comapany person mobile-no')),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_status', models.CharField(max_length=5)),
                ('d_add', models.TextField(max_length=100, null=True)),
                ('amt_status', models.CharField(blank=True, max_length=15, null=True)),
                ('totel_amt', models.CharField(help_text='totel amount of product', max_length=10)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.customer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('o_d_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('pay_status', models.CharField(blank=True, max_length=15, null=True)),
                ('rate', models.CharField(help_text='the totel amount of product', max_length=10)),
                ('o_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.customer_order')),
                ('p_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Product_View')),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_add', models.TextField(default='none', max_length=120, null=True)),
                ('d_amt', models.CharField(max_length=10)),
                ('d_a_status', models.CharField(blank=True, max_length=15, null=True)),
                ('d_status', models.CharField(max_length=10)),
                ('e_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_master.employee_master')),
                ('o_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.customer_order')),
            ],
        ),
    ]
