# Generated by Django 2.2.5 on 2020-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0002_auto_20200129_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='amt_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
