# Generated by Django 2.2.5 on 2020-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0003_customer_order_amt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='amt_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='amt_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
