# Generated by Django 2.2.5 on 2020-01-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0004_auto_20200129_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='ppid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstatus', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
