# Generated by Django 2.2.5 on 2020-01-29 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0005_ppid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='pay_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.ppid'),
        ),
    ]
