# Generated by Django 2.2.5 on 2020-01-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0006_customer_order_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pay_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.ppid'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='pay_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.ppid'),
        ),
    ]
