# Generated by Django 2.2.5 on 2020-01-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0007_auto_20200129_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='amt_status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='amt_status',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='amt_status',
        ),
    ]
