# Generated by Django 2.2.5 on 2020-02-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0008_auto_20200129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='pay_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.ppid'),
        ),
        migrations.AlterField(
            model_name='customer_order',
            name='totel_amt',
            field=models.CharField(blank=True, help_text='totel amount of product', max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pay_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.ppid'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='pay_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.ppid'),
        ),
    ]
