# Generated by Django 2.2.5 on 2020-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0009_auto_20200206_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='p_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
