# Generated by Django 2.2.5 on 2020-02-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0010_auto_20200214_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='o_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_order'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='o_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_order'),
        ),
    ]
