# Generated by Django 2.2.5 on 2020-02-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0013_inquery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery_order',
            name='a_Description',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquery_order',
            name='a_status',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquery_order',
            name='c_Description',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inquery_order',
            name='i_img',
            field=models.ImageField(blank=True, null=True, upload_to='inq_pic'),
        ),
        migrations.AlterField(
            model_name='inquery_order',
            name='price',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inquery_order',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
