# Generated by Django 2.2.5 on 2020-02-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0015_auto_20200229_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery_order',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
