# Generated by Django 2.2.5 on 2020-02-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0016_auto_20200229_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery_order',
            name='c_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_detail'),
        ),
        migrations.AlterField(
            model_name='inquery_order',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
