# Generated by Django 2.2.5 on 2020-03-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0019_auto_20200301_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquery_order',
            name='c_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
