# Generated by Django 2.2.5 on 2020-03-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0020_inquery_order_c_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='p_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
