# Generated by Django 2.2.5 on 2020-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0022_order_detail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pay_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='pay_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
