# Generated by Django 2.2.5 on 2020-03-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0023_auto_20200303_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='pendding_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
