# Generated by Django 2.2.5 on 2020-03-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0024_customer_order_pendding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_order',
            name='pendding_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
