# Generated by Django 2.2.5 on 2020-03-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0025_auto_20200303_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='pay_status',
        ),
    ]
