# Generated by Django 2.2.5 on 2020-03-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0026_remove_order_detail_pay_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_order',
            name='d_add',
        ),
        migrations.RemoveField(
            model_name='customer_order',
            name='pendding_amount',
        ),
    ]
