# Generated by Django 2.2.5 on 2020-03-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0027_auto_20200303_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='d_add',
            field=models.TextField(blank=True, default='none', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='d_amt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='d_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='e_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_master.employee_master'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='o_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_order'),
        ),
    ]
