# Generated by Django 2.2.5 on 2020-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0028_auto_20200305_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
