# Generated by Django 2.2.5 on 2020-03-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0030_customer_order_order_competio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_order',
            old_name='order_competio',
            new_name='order_completion',
        ),
    ]
