# Generated by Django 2.2.5 on 2020-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0031_auto_20200308_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
