# Generated by Django 2.2.5 on 2020-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0032_order_detail_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='d_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
