# Generated by Django 2.2.5 on 2020-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0034_auto_20200413_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='pay_price',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
