# Generated by Django 2.2.5 on 2020-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0037_auto_20200426_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_detail',
            name='com_per_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='comapany name'),
        ),
    ]
