# Generated by Django 2.2.5 on 2020-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0039_customer_detail_com_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='com_per_name',
        ),
    ]
