# Generated by Django 2.2.5 on 2019-12-13 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('product_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_color', models.CharField(max_length=20)),
                ('p_description', models.TextField()),
                ('p_code', models.CharField(max_length=10)),
                ('p_weight', models.FloatField()),
                ('p_price', models.FloatField()),
                ('p_img', models.ImageField(upload_to='')),
                ('p_hight', models.FloatField()),
                ('p_width', models.FloatField()),
                ('product_type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Product_Type')),
            ],
        ),
    ]
