# Generated by Django 2.2.5 on 2020-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_view',
            name='p_color',
        ),
        migrations.AddField(
            model_name='product_view',
            name='p_dis',
            field=models.CharField(default='none', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='product_type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_view',
            name='p_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product_view',
            name='p_img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
