# Generated by Django 2.2.5 on 2020-01-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20200112_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product_view',
            name='p_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.color'),
        ),
    ]
