# Generated by Django 2.2.5 on 2020-01-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_gadge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gadge',
        ),
    ]
