# Generated by Django 2.2.5 on 2020-03-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0020_inquery_order_c_no'),
        ('category', '0005_delete_gadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type_id', models.CharField(blank=True, max_length=10, null=True)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='custom_pics')),
                ('p_description', models.TextField(blank=True, max_length=5, null=True)),
                ('p_color', models.CharField(blank=True, max_length=10, null=True)),
                ('p_price', models.FloatField(blank=True, null=True)),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer_detail')),
            ],
        ),
    ]
