# Generated by Django 2.2.5 on 2020-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_custom_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_product',
            name='iqu_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
