# Generated by Django 2.2.5 on 2020-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_custom_product_iqu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_product',
            name='p_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
