# Generated by Django 2.2.5 on 2020-01-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_info', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_des', models.CharField(max_length=20)),
                ('c_img', models.ImageField(upload_to='user_pics')),
                ('img_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_info.customer_detail')),
            ],
        ),
    ]
