# Generated by Django 2.2.5 on 2020-02-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0002_remove_customer_img_c_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.TextField(max_length=20)),
                ('modifiction', models.TextField(blank=True, max_length=20, null=True)),
                ('d_status', models.TextField(blank=True, max_length=3, null=True)),
                ('p_id', models.TextField(max_length=20)),
                ('qty', models.TextField(max_length=20)),
            ],
        ),
    ]
