# Generated by Django 2.2.5 on 2020-02-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0003_temp_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_cart',
            name='d_status',
        ),
        migrations.RemoveField(
            model_name='temp_cart',
            name='qty',
        ),
    ]
