# Generated by Django 2.2.5 on 2020-02-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0004_auto_20200206_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_cart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
