# Generated by Django 2.2.5 on 2020-02-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0007_temp_cart_totel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_cart',
            name='p_id',
            field=models.TextField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
