# Generated by Django 2.2.5 on 2020-02-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0010_auto_20200208_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_cart',
            name='p_name',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
