# Generated by Django 2.2.5 on 2020-03-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0014_auto_20200304_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid_qr',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
