# Generated by Django 2.2.5 on 2020-03-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0015_auto_20200304_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oid_qr',
            old_name='qr',
            new_name='qrimg',
        ),
    ]
