# Generated by Django 2.2.5 on 2020-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0016_auto_20200304_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oid_qr',
            name='qrimg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
