# Generated by Django 2.2.5 on 2020-04-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userimg', '0018_auto_20200304_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oid_qr',
        ),
    ]
