# Generated by Django 2.2.5 on 2019-12-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_master',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=10)),
                ('e_add', models.CharField(max_length=100)),
                ('e_con_no', models.IntegerField()),
                ('e_desig', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
