# Generated by Django 2.2.5 on 2019-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_master',
            name='e_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
