# Generated by Django 2.2.5 on 2020-01-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_gadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_price', models.IntegerField(max_length=10)),
                ('r_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.color')),
            ],
        ),
    ]
