# Generated by Django 2.2.5 on 2020-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gadge', models.TextField(max_length=3)),
            ],
        ),
    ]
