# Generated by Django 2.2.5 on 2020-01-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_gadge'),
        ('raw_material', '0002_gadge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='raw_material',
            new_name='Color',
        ),
    ]
