# Generated by Django 2.2.5 on 2020-01-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_auto_20200121_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='r_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='r_price',
            new_name='price',
        ),
    ]
