# Generated by Django 2.2.5 on 2020-01-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_delete_gadge'),
        ('raw_material', '0005_gadge_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='PColor',
        ),
    ]
