# Generated by Django 2.2.5 on 2020-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0006_auto_20200123_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadge',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pcolor',
            name='price',
            field=models.IntegerField(),
        ),
    ]
