# Generated by Django 2.2.5 on 2020-02-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_auto_20200129_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gadge',
        ),
    ]
